In [2]:
import pandas as pd

df = pd.read_csv(r"D:\Code\Project\EMIPredict-AI\data\emi_cleaned.csv")
print(df.shape)
df.head()

(404800, 27)

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,...,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,...,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

In [3]:
categorical_cols = ['gender', 'marital_status', 'education', 'employment_type', 'company_type', 
                     'house_type', 'existing_loans', 'emi_scenario']

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df_encoded.shape

(404800, 37)

In [4]:
df['total_monthly_expense'] = (
    df['school_fees'] +
    df['college_fees'] +
    df['travel_expenses'] +
    df['groceries_utilities'] +
    df['other_monthly_expenses']
)

In [5]:
df['debt_to_income'] = (df['current_emi_amount'] + df['monthly_rent']) / df['monthly_salary']
df['expense_to_income'] = df['total_monthly_expense'] / df['monthly_salary']
df['affordability_ratio'] = df['monthly_salary'] - df['total_monthly_expense'] - df['current_emi_amount'] - df['monthly_rent']

df[['debt_to_income', 'expense_to_income', 'affordability_ratio']].describe()

       debt_to_income  expense_to_income  affordability_ratio
count   404800.000000      404800.000000        404800.000000
mean         0.191322           0.675865         14831.331744
std          0.245613           0.494049         37581.517747
min          0.000000           0.011144       -161883.000000
25%          0.000000           0.467401           400.000000
50%          0.183817           0.573551         10600.000000
75%          0.288660           0.751497         22400.000000
max         16.297906          21.744305        485540.000000

In [6]:
categorical_cols = ['gender', 'marital_status', 'education', 'employment_type', 'company_type', 
                     'house_type', 'existing_loans', 'emi_scenario']

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df_encoded.shape

(404800, 41)

In [7]:
from sklearn.preprocessing import StandardScaler

numeric_features = ['age', 'monthly_salary', 'years_of_employment', 'monthly_rent', 'family_size',
                     'dependents', 'total_monthly_expense', 'current_emi_amount', 'credit_score',
                     'bank_balance', 'emergency_fund', 'requested_amount', 'requested_tenure',
                     'debt_to_income', 'expense_to_income', 'affordability_ratio']

scaler = StandardScaler()
df_encoded[numeric_features] = scaler.fit_transform(df_encoded[numeric_features])
df_encoded[numeric_features].describe()

,age,monthly_salary,years_of_employment,monthly_rent,family_size,dependents,total_monthly_expense,current_emi_amount,credit_score,bank_balance,emergency_fund,requested_amount,requested_tenure,debt_to_income,expense_to_income,affordability_ratio
count,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05,4.048000e+05
mean,-3.240974e-16,7.603931e-17,-1.649274e-16,3.159528e-17,1.348065e-16,-4.999075e-17,2.027013e-16,3.875688e-17,-6.406118e-16,1.404235e-18,6.305014e-17,-3.812497e-17,6.831602e-17,9.647092e-17,1.797420e-17,-2.625919e-17
std,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00
min,-1.383973e+00,-1.282297e+00,-8.001279e-01,-6.709834e-01,-1.804714e+00,-1.804714e+00,-1.892849e+00,-6.458390e-01,-7.948866e+00,-1.289729e+00,-1.173521e+00,-1.045370e+00,-1.443396e+00,-7.789581e-01,-1.345458e+00,-4.702166e+00
25%,-7.390558e-01,-5.561055e-01,-6.849798e-01,-6.709834e-01,-8.746528e-01,-8.746528e-01,-7.413110e-01,-6.458390e-01,-5.314360e-01,-7.454552e-01,-7.151376e-01,-7.151206e-01,-7.804435e-01,-7.789581e-01,-4.219511e-01,-3.840012e-01
50%,-9.413904e-02,-1.795295e-01,-3.559852e-01,-6.709834e-01,5.540849e-02,5.540849e-02,-1.410412e-01,-6.458390e-01,1.620918e-03,-2.483667e-01,-2.789339e-01,-3.906654e-01,-2.279827e-01,-3.055349e-02,-2.070929e-01,-1.125909e-01
75%,9.807222e-01,3.079400e-01,3.020040e-01,5.566690e-01,9.854698e-01,9.854698e-01,5.878580e-01,4.913497e-01,5.346778e-01,4.830010e-01,4.135702e-01,3.567402e-01,6.007084e-01,3.963083e-01,1.530859e-01,2.013936e-01
max,2.163070e+00,1.017677e+01,5.039526e+00,8.594318e+00,1.915531e+00,1.915531e+00,7.644092e+00,7.357126e+00,5.661098e+00,8.098991e+00,9.794413e+00,3.271043e+00,3.031536e+00,6.557729e+01,4.264449e+01,1.252502e+01

In [8]:
from sklearn.model_selection import train_test_split

X = df_encoded.drop(columns=['emi_eligibility', 'max_monthly_emi'])
y_class = df_encoded['emi_eligibility']
y_reg = df_encoded['max_monthly_emi']

X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_class, y_reg, test_size=0.2, random_state=42, stratify=y_class
)

print(X_train.shape, X_test.shape)

(323840, 39) (80960, 39)

In [9]:
mlflow.set_tracking_uri("sqlite:///D:/Code/Project/EMIPredict-AI/mlruns/mlflow.db")

experiment_name = "EMIPredict_Classification_final"
mlflow.create_experiment(
    experiment_name,
    artifact_location="file:///D:/Code/Project/EMIPredict-AI/mlruns"
)
mlflow.set_experiment(experiment_name)

MlflowException: Experiment(name=EMIPredict_Classification_final) already exists. Error: (sqlite3.IntegrityError) UNIQUE constraint failed: experiments.workspace, experiments.name
[SQL: INSERT INTO experiments (name, workspace, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('EMIPredict_Classification_final', 'default', 'file:///D:/Code/Project/EMIPredict-AI/mlruns', 'active', 1785694072882, 1785694072882)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

with mlflow.start_run(run_name="Logistic_Regression"):
    lr = LogisticRegression(max_iter=1000, random_state=42)
    lr.fit(X_train, y_class_train)
    
    y_pred = lr.predict(X_test)
    
    acc = accuracy_score(y_class_test, y_pred)
    prec = precision_score(y_class_test, y_pred, average='weighted')
    rec = recall_score(y_class_test, y_pred, average='weighted')
    f1 = f1_score(y_class_test, y_pred, average='weighted')
    
    mlflow.log_param("model", "LogisticRegression")
    mlflow.log_metric("accuracy", acc)
    mlflow.log_metric("precision", prec)
    mlflow.log_metric("recall", rec)
    mlflow.log_metric("f1_score", f1)
    mlflow.sklearn.log_model(lr, "model")
    
    print(f"Accuracy: {acc:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}, F1: {f1:.4f}")

d:\Code\Project\EMIPredict-AI\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
2026/08/02 06:04:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Accuracy: 0.8796, Precision: 0.8469, Recall: 0.8796, F1: 0.8591

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# --- Random Forest (baseline) ---
with mlflow.start_run(run_name="Random_Forest"):
    rf = RandomForestClassifier(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)
    rf.fit(X_train, y_class_train)
    y_pred = rf.predict(X_test)

    mlflow.log_param("model", "RandomForest")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 15)
    mlflow.log_metric("accuracy", accuracy_score(y_class_test, y_pred))
    mlflow.log_metric("precision", precision_score(y_class_test, y_pred, average='weighted'))
    mlflow.log_metric("recall", recall_score(y_class_test, y_pred, average='weighted'))
    mlflow.log_metric("f1_score", f1_score(y_class_test, y_pred, average='weighted'))
    mlflow.sklearn.log_model(rf, "model")

    print("=== Random Forest (baseline) ===")
    print(classification_report(y_class_test, y_pred))

# --- Random Forest (class-balanced) ---
with mlflow.start_run(run_name="Random_Forest_Balanced"):
    rf_bal = RandomForestClassifier(n_estimators=100, max_depth=15, class_weight='balanced', random_state=42, n_jobs=-1)
    rf_bal.fit(X_train, y_class_train)
    y_pred_bal = rf_bal.predict(X_test)

    mlflow.log_param("model", "RandomForest_Balanced")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 15)
    mlflow.log_param("class_weight", "balanced")
    mlflow.log_metric("accuracy", accuracy_score(y_class_test, y_pred_bal))
    mlflow.log_metric("precision", precision_score(y_class_test, y_pred_bal, average='weighted'))
    mlflow.log_metric("recall", recall_score(y_class_test, y_pred_bal, average='weighted'))
    mlflow.log_metric("f1_score", f1_score(y_class_test, y_pred_bal, average='weighted'))
    mlflow.sklearn.log_model(rf_bal, "model")

    print("=== Random Forest (class-balanced) ===")
    print(classification_report(y_class_test, y_pred_bal))

d:\Code\Project\EMIPredict-AI\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
2026/08/02 06:05:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

=== Random Forest (baseline) ===

d:\Code\Project\EMIPredict-AI\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Code\Project\EMIPredict-AI\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Code\Project\EMIPredict-AI\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score   support

    Eligible       0.89      0.91      0.90     14889
   High_Risk       0.00      0.00      0.00      3497
Not_Eligible       0.94      0.99      0.97     62574

    accuracy                           0.93     80960
   macro avg       0.61      0.63      0.62     80960
weighted avg       0.89      0.93      0.91     80960

2026/08/02 06:06:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

=== Random Forest (class-balanced) ===
              precision    recall  f1-score   support

    Eligible       0.87      0.84      0.86     14889
   High_Risk       0.23      0.67      0.34      3497
Not_Eligible       0.99      0.89      0.94     62574

    accuracy                           0.87     80960
   macro avg       0.70      0.80      0.71     80960
weighted avg       0.94      0.87      0.90     80960

In [43]:
import xgboost as xgb
import mlflow.xgboost
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

le = LabelEncoder()
y_class_train_enc = le.fit_transform(y_class_train)
y_class_test_enc = le.transform(y_class_test)

sample_weights = compute_sample_weight(class_weight='balanced', y=y_class_train_enc)

with mlflow.start_run(run_name="XGBoost_Balanced"):
    xgb_clf = xgb.XGBClassifier(
        n_estimators=100,
        max_depth=6,
        learning_rate=0.1,
        random_state=42,
        n_jobs=-1,
        eval_metric='mlogloss'
    )
    xgb_clf.fit(X_train, y_class_train_enc, sample_weight=sample_weights)
    y_pred_xgb_enc = xgb_clf.predict(X_test)

    mlflow.log_param("model", "XGBoost_Balanced")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 6)
    mlflow.log_param("learning_rate", 0.1)
    mlflow.log_param("class_weight", "balanced (via sample_weight)")
    mlflow.log_metric("accuracy", accuracy_score(y_class_test_enc, y_pred_xgb_enc))
    mlflow.log_metric("precision", precision_score(y_class_test_enc, y_pred_xgb_enc, average='weighted'))
    mlflow.log_metric("recall", recall_score(y_class_test_enc, y_pred_xgb_enc, average='weighted'))
    mlflow.log_metric("f1_score", f1_score(y_class_test_enc, y_pred_xgb_enc, average='weighted'))
    mlflow.xgboost.log_model(xgb_clf, "model")

    print("=== XGBoost (class-balanced) ===")
    print(classification_report(y_class_test_enc, y_pred_xgb_enc, target_names=le.classes_))

2026/08/02 06:11:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

=== XGBoost (class-balanced) ===
              precision    recall  f1-score   support

    Eligible       0.97      0.84      0.90     14889
   High_Risk       0.27      0.94      0.42      3497
Not_Eligible       1.00      0.89      0.94     62574

    accuracy                           0.88     80960
   macro avg       0.75      0.89      0.75     80960
weighted avg       0.96      0.88      0.91     80960

In [44]:
from sklearn.model_selection import train_test_split

y_reg = df_encoded['max_monthly_emi']

y_reg_train, y_reg_test = train_test_split(
    y_reg, test_size=0.2, stratify=y_class, random_state=42
)

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# ---------- 1. TRAIN LINEAR REGRESSION ----------
with mlflow.start_run(run_name="Linear_Regression"):
    lr_reg = LinearRegression()
    lr_reg.fit(X_train, y_reg_train)
    y_pred_lr = lr_reg.predict(X_test)

    mlflow.log_param("model", "LinearRegression")
    mlflow.log_metric("rmse", np.sqrt(mean_squared_error(y_reg_test, y_pred_lr)))
    mlflow.log_metric("mae", mean_absolute_error(y_reg_test, y_pred_lr))
    mlflow.log_metric("r2", r2_score(y_reg_test, y_pred_lr))
    mlflow.sklearn.log_model(lr_reg, "model")

# ---------- 2. TRAIN RANDOM FOREST REGRESSOR ----------
with mlflow.start_run(run_name="Random_Forest_Regressor"):
    rf_reg = RandomForestRegressor(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)
    rf_reg.fit(X_train, y_reg_train)
    y_pred_rf = rf_reg.predict(X_test)

    mlflow.log_param("model", "RandomForestRegressor")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 15)
    mlflow.log_metric("rmse", np.sqrt(mean_squared_error(y_reg_test, y_pred_rf)))
    mlflow.log_metric("mae", mean_absolute_error(y_reg_test, y_pred_rf))
    mlflow.log_metric("r2", r2_score(y_reg_test, y_pred_rf))
    mlflow.sklearn.log_model(rf_reg, "model")

# ---------- 3. TRAIN XGBOOST REGRESSOR ----------
with mlflow.start_run(run_name="XGBoost_Regressor"):
    xgb_reg = xgb.XGBRegressor(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42, n_jobs=-1)
    xgb_reg.fit(X_train, y_reg_train)
    y_pred_xgb = xgb_reg.predict(X_test)

    mlflow.log_param("model", "XGBoostRegressor")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 6)
    mlflow.log_param("learning_rate", 0.1)
    mlflow.log_metric("rmse", np.sqrt(mean_squared_error(y_reg_test, y_pred_xgb)))
    mlflow.log_metric("mae", mean_absolute_error(y_reg_test, y_pred_xgb))
    mlflow.log_metric("r2", r2_score(y_reg_test, y_pred_xgb))
    mlflow.xgboost.log_model(xgb_reg, "model")

# ---------- 4. EVALUATION FUNCTION ----------
def evaluate_regression(y_true, y_pred, model_name):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    print(f"\n{model_name}")
    print("RMSE :", rmse)
    print("MAE  :", mae)
    print("R²   :", r2)

# ---------- 5. MODEL EVALUATION ----------
y_test_r = y_reg_test

evaluate_regression(y_test_r, y_pred_lr, "Linear Regression")
evaluate_regression(y_test_r, y_pred_rf, "Random Forest Regressor")
evaluate_regression(y_test_r, y_pred_xgb, "XGBoost Regressor")

2026/08/02 06:13:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/02 06:16:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/02 06:17:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Linear Regression
RMSE : 4143.802814368121
MAE  : 2982.14958225878
R²   : 0.7157489477840489

Random Forest Regressor
RMSE : 1046.8375089027802
MAE  : 367.98277757084674
R²   : 0.981858947943424

XGBoost Regressor
RMSE : 836.9692425069769
MAE  : 348.96973398771996
R²   : 0.9884036072425166

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
)

# Encode labels for models that need numeric classes (XGBoost)
le = LabelEncoder()
y_train_enc = le.fit_transform(y_class_train)
y_test_enc = le.transform(y_class_test)

def evaluate_model(y_true, y_pred, y_prob, model_name):
    print(f"\n{model_name}")
    print("Accuracy :", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred, average='weighted'))
    print("Recall   :", recall_score(y_true, y_pred, average='weighted'))
    print("F1 Score :", f1_score(y_true, y_pred, average='weighted'))
    print("ROC-AUC  :", roc_auc_score(y_true, y_prob, multi_class='ovr'))

# ---------- LOGISTIC REGRESSION ----------
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_class_train)
y_pred_lr = log_reg.predict(X_test)
y_prob_lr = log_reg.predict_proba(X_test)
evaluate_model(y_class_test, y_pred_lr, y_prob_lr, "Logistic Regression")

# ---------- RANDOM FOREST ----------
rf_clf = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42, n_jobs=-1)
rf_clf.fit(X_train, y_class_train)
y_pred_rf = rf_clf.predict(X_test)
y_prob_rf = rf_clf.predict_proba(X_test)
evaluate_model(y_class_test, y_pred_rf, y_prob_rf, "Random Forest")

# ---------- XGBOOST ----------
xgb_clf = XGBClassifier(
    n_estimators=300, learning_rate=0.05, max_depth=6,
    subsample=0.8, colsample_bytree=0.8,
    objective='multi:softprob', eval_metric='mlogloss',
    random_state=42, n_jobs=-1
)
xgb_clf.fit(X_train, y_train_enc)
y_pred_xgb_enc = xgb_clf.predict(X_test)
y_prob_xgb = xgb_clf.predict_proba(X_test)
y_pred_xgb = le.inverse_transform(y_pred_xgb_enc)
evaluate_model(y_class_test, y_pred_xgb, y_prob_xgb, "XGBoost")

d:\Code\Project\EMIPredict-AI\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
Accuracy : 0.8795701581027668
Precision: 0.846870843299017
Recall   : 0.8795701581027668
F1 Score : 0.8591355963815768
ROC-AUC  : 0.9055448460935405

Random Forest
Accuracy : 0.9114006916996047

d:\Code\Project\EMIPredict-AI\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Precision: 0.8709787320190939
Recall   : 0.9114006916996047
F1 Score : 0.8902008627559688
ROC-AUC  : 0.9468713314287096

XGBoost
Accuracy : 0.9570528656126482
Precision: 0.9529132179569297
Recall   : 0.9570528656126482
F1 Score : 0.942893261993225
ROC-AUC  : 0.989764091467691

In [47]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_class_test, y_pred_xgb))
print(confusion_matrix(y_class_test, y_pred_xgb))

              precision    recall  f1-score   support

    Eligible       0.92      0.98      0.95     14889
   High_Risk       0.84      0.12      0.21      3497
Not_Eligible       0.97      1.00      0.98     62574

    accuracy                           0.96     80960
   macro avg       0.91      0.70      0.71     80960
weighted avg       0.95      0.96      0.94     80960

[[14627    61   201]
 [ 1233   413  1851]
 [  112    19 62443]]

In [48]:
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import mlflow.xgboost
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# --- Random Forest (balanced) ---
with mlflow.start_run(run_name="Random_Forest_Balanced"):
    rf_bal = RandomForestClassifier(n_estimators=100, max_depth=15, class_weight='balanced', random_state=42, n_jobs=-1)
    rf_bal.fit(X_train, y_class_train)
    y_pred_rf = rf_bal.predict(X_test)

    mlflow.log_param("model", "RandomForest_Balanced")
    mlflow.log_param("class_weight", "balanced")
    mlflow.log_metric("accuracy", accuracy_score(y_class_test, y_pred_rf))
    mlflow.log_metric("f1_score", f1_score(y_class_test, y_pred_rf, average='weighted'))
    mlflow.sklearn.log_model(rf_bal, "model")
    print("=== Random Forest (Balanced) ===")
    print(classification_report(y_class_test, y_pred_rf))

# --- XGBoost (balanced) ---
le = LabelEncoder()
y_class_train_enc = le.fit_transform(y_class_train)
y_class_test_enc = le.transform(y_class_test)
sample_weights = compute_sample_weight(class_weight='balanced', y=y_class_train_enc)

with mlflow.start_run(run_name="XGBoost_Balanced"):
    xgb_clf = xgb.XGBClassifier(
        n_estimators=100, max_depth=6, learning_rate=0.1,
        random_state=42, n_jobs=-1, eval_metric='mlogloss'
    )
    xgb_clf.fit(X_train, y_class_train_enc, sample_weight=sample_weights)
    y_pred_xgb_enc = xgb_clf.predict(X_test)

    mlflow.log_param("model", "XGBoost_Balanced")
    mlflow.log_param("class_weight", "balanced (via sample_weight)")
    mlflow.log_metric("accuracy", accuracy_score(y_class_test_enc, y_pred_xgb_enc))
    mlflow.log_metric("f1_score", f1_score(y_class_test_enc, y_pred_xgb_enc, average='weighted'))
    mlflow.xgboost.log_model(xgb_clf, "model")
    print("=== XGBoost (Balanced) ===")
    print(classification_report(y_class_test_enc, y_pred_xgb_enc, target_names=le.classes_))

2026/08/02 06:32:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

=== Random Forest (Balanced) ===
              precision    recall  f1-score   support

    Eligible       0.87      0.84      0.86     14889
   High_Risk       0.23      0.67      0.34      3497
Not_Eligible       0.99      0.89      0.94     62574

    accuracy                           0.87     80960
   macro avg       0.70      0.80      0.71     80960
weighted avg       0.94      0.87      0.90     80960

2026/08/02 06:33:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

=== XGBoost (Balanced) ===
              precision    recall  f1-score   support

    Eligible       0.97      0.84      0.90     14889
   High_Risk       0.27      0.94      0.42      3497
Not_Eligible       1.00      0.89      0.94     62574

    accuracy                           0.88     80960
   macro avg       0.75      0.89      0.75     80960
weighted avg       0.96      0.88      0.91     80960

In [49]:
import joblib

joblib.dump(xgb_clf, "../models/emi_eligibility_classifier.pkl")
joblib.dump(xgb_reg, "../models/max_emi_regressor.pkl")
joblib.dump(le, "../models/label_encoder.pkl")
joblib.dump(scaler, "../models/feature_scaler.pkl")

['../models/feature_scaler.pkl']

In [12]:
clf_run_id = "7ce6016abd1a4c079b244817d8d776b9"
reg_run_id = "27aa65517ff1428dbe6de748459e3bbb"

mlflow.register_model(f"runs:/{clf_run_id}/model", "EMI_Eligibility_Classifier")
mlflow.register_model(f"runs:/{reg_run_id}/model", "Max_EMI_Regressor")

Successfully registered model 'EMI_Eligibility_Classifier'.
2026/08/02 23:40:53 WARNING mlflow.tracking._model_registry.fluent: Run with id 7ce6016abd1a4c079b244817d8d776b9 has no artifacts at artifact path 'model', registering model based on models:/m-34417631b1734d3fa13841fce4cbaadb instead
Created version '1' of model 'EMI_Eligibility_Classifier'.
Successfully registered model 'Max_EMI_Regressor'.
2026/08/02 23:40:53 WARNING mlflow.tracking._model_registry.fluent: Run with id 27aa65517ff1428dbe6de748459e3bbb has no artifacts at artifact path 'model', registering model based on models:/m-fba4c1932cfe49d79ed0ba747ed3f055 instead
Created version '1' of model 'Max_EMI_Regressor'.

<ModelVersion: aliases=[], creation_timestamp=1785694253704, current_stage='None', deployment_job_state=None, description=None, last_updated_timestamp=1785694253704, metrics=None, model_id=None, name='Max_EMI_Regressor', params=None, run_id='27aa65517ff1428dbe6de748459e3bbb', run_link=None, source='models:/m-fba4c1932cfe49d79ed0ba747ed3f055', status='READY', status_message=None, tags={}, user_id=None, version=1, workspace='default'>

In [13]:
for name in ["EMI_Eligibility_Classifier", "Max_EMI_Regressor"]:
    for v in client.search_model_versions(f"name='{name}'"):
        print(v.name, v.version, v.run_id, v.current_stage)

EMI_Eligibility_Classifier 1 7ce6016abd1a4c079b244817d8d776b9 None
Max_EMI_Regressor 1 27aa65517ff1428dbe6de748459e3bbb None